export const OPERATION_TYPES_TRANSLATION = {
    MarketplaceServiceItemCrossdocking: 'Сервис маркетплейса: кроссдокинг (перемещение товара через склад без хранения)',
    MarketplaceRedistributionOfAcquiringOperation: 'Перераспределение комиссий эквайринга (банковские операции с оплатой)',
    MarketplaceServiceItemDelivToCustomer: 'Сервис маркетплейса: доставка товара покупателю',
    MarketplaceServiceItemDirectFlowLogisticVDC: 'Сервис маркетплейса: прямая логистика (VDC)',
    SaleCommission: 'Комиссия за продажу',
    MarketplaceServiceItemReturnNotDelivToCustomer: 'Сервис маркетплейса: возврат товара, не доставленного покупателю',
    MarketplaceServiceItemReturnFlowLogistic: 'Сервис маркетплейса: логистика возвратного потока',
    MarketplaceServiceItemRedistributionReturnsPVZ: 'Сервис маркетплейса: перераспределение возвратов в пункт выдачи заказов (ПВЗ)',
    ClientReturnAgentOperation: 'Операция возврата от покупателя',
    MarketplaceServiceItemReturnAfterDelivToCustomer: 'Сервис маркетплейса: возврат после доставки покупателю',
    MarketplaceSaleReviewsOperation: 'Операция: отзывы о продаже',
    OperationSubscriptionPremium: 'Подписка Premium',
    MarketplaceServiceItemElectronicServicesPremiumCashbackIndividualPoints:
        'Сервис маркетплейса: электронные услуги, премиум-кэшбэк, индивидуальные баллы',
    OperationMarketplaceServiceEarlyPaymentAccrual: 'Сервис маркетплейса: начисление за досрочную выплату',
    ItemAgentServiceStarsMembership: 'Сервис агентский: участие в программе «звёздное» (Stars Membership)',
    OperationMarketplaceServiceSupplyInboundCargoShortage: 'Сервис маркетплейса: недостача груза при поставке',
    MarketplaceServiceItemDirectFlowLogistic: 'Сервис маркетплейса: прямая логистика',
    MarketplaceServiceItemInstallment: 'Сервис маркетплейса: рассрочка',
    OperationPointsForReviews: 'Начисление баллов за отзывы',
    OperationMarketplaceSupplyExpirationDateProcessing: 'Сервис маркетплейса: обработка товара с истекшим сроком годности',
    MarketplaceServiceSellerReturnsCargoAssortment: 'Сервис маркетплейса: возврат груза продавцу по ассортименту',
    MarketplaceServiceProductMovementFromWarehouse: 'Сервис маркетплейса: перемещение товара со склада',
    OperationMarketplaceSupplyAdditional: 'Сервис маркетплейса: дополнительные операции по поставке',
    OperationPromotionWithCostPerOrder: 'Продвижение с оплатой за заказ (CPO)',
    OperationMarketplaceServiceSupplyInboundCargoSurplus: 'Сервис маркетплейса: излишек груза при поставке',
    MarketplaceSellerCorrectionOperation: 'Корректировка со стороны продавца',
    MarketplaceCorrectionPointOperation: 'Корректировка баллов',
    MarketplaceServiceItemRedistributionLastMileCourier: 'Сервис маркетплейса: перераспределение расходов последней мили (курьер)',
    MarketplaceServiceItemRedistributionLastMilePVZ: 'Сервис маркетплейса: перераспределение расходов последней мили (ПВЗ)',
    OperationMarketPlaceItemPinReview: 'Платная фиксация отзыва (pin review)',
    MarketplaceServiceItemReturnPartGoodsCustomer: 'Сервис маркетплейса: частичный возврат товара покупателем',
    MarketplaceServiceItemDisposalDetailed: 'Сервис маркетплейса: утилизация товара (детализированная)',
    MarketplaceServiceBrandCommission: 'Сервис маркетплейса: брендовая комиссия',
    MarketplaceServiceItemPackageMaterialsProvision: 'Сервис маркетплейса: предоставление упаковочных материалов',
    MarketplaceServiceItemPackageRedistribution: 'Сервис маркетплейса: перераспределение упаковки',
};
