export const OPERATION_TYPES_TRANSLATION = {
    MarketplaceServiceItemCrossdocking: 'Кроссдокинг (перемещение товара через склад без хранения)',
    MarketplaceRedistributionOfAcquiringOperation: 'Перераспределение комиссий эквайринга (банковские операции с оплатой)',
    MarketplaceServiceItemDelivToCustomer: 'доставка товара покупателю',
    MarketplaceServiceItemDirectFlowLogisticVDC: 'прямая логистика (VDC)',
    SaleCommission: 'Комиссия за продажу',
    MarketplaceServiceItemReturnNotDelivToCustomer: 'возврат товара, не доставленного покупателю',
    MarketplaceServiceItemReturnFlowLogistic: 'логистика возвратного потока',
    MarketplaceServiceItemRedistributionReturnsPVZ: 'перераспределение возвратов в пункт выдачи заказов (ПВЗ)',
    ClientReturnAgentOperation: 'Операция возврата от покупателя',
    MarketplaceServiceItemReturnAfterDelivToCustomer: 'возврат после доставки покупателю',
    MarketplaceSaleReviewsOperation: 'Операция: отзывы о продаже',
    OperationSubscriptionPremium: 'Подписка Premium',
    MarketplaceServiceItemElectronicServicesPremiumCashbackIndividualPoints:
        'электронные услуги, премиум-кэшбэк, индивидуальные баллы',
    OperationMarketplaceServiceEarlyPaymentAccrual: 'начисление за досрочную выплату',
    ItemAgentServiceStarsMembership: 'Сервис агентский: участие в программе «звёздное» (Stars Membership)',
    OperationMarketplaceServiceSupplyInboundCargoShortage: 'недостача груза при поставке',
    MarketplaceServiceItemDirectFlowLogistic: 'прямая логистика',
    MarketplaceServiceItemInstallment: 'рассрочка',
    OperationPointsForReviews: 'Начисление баллов за отзывы',
    OperationMarketplaceSupplyExpirationDateProcessing: 'обработка товара с истекшим сроком годности',
    MarketplaceServiceSellerReturnsCargoAssortment: 'возврат груза продавцу по ассортименту',
    MarketplaceServiceProductMovementFromWarehouse: 'перемещение товара со склада',
    OperationMarketplaceSupplyAdditional: 'дополнительные операции по поставке',
    OperationPromotionWithCostPerOrder: 'Продвижение с оплатой за заказ (CPO)',
    OperationMarketplaceServiceSupplyInboundCargoSurplus: 'излишек груза при поставке',
    MarketplaceSellerCorrectionOperation: 'Корректировка со стороны продавца',
    MarketplaceCorrectionPointOperation: 'Корректировка баллов',
    MarketplaceServiceItemRedistributionLastMileCourier: 'перераспределение расходов последней мили (курьер)',
    MarketplaceServiceItemRedistributionLastMilePVZ: 'перераспределение расходов последней мили (ПВЗ)',
    OperationMarketPlaceItemPinReview: 'Платная фиксация отзыва (pin review)',
    MarketplaceServiceItemReturnPartGoodsCustomer: 'частичный возврат товара покупателем',
    MarketplaceServiceItemDisposalDetailed: 'утилизация товара (детализированная)',
    MarketplaceServiceBrandCommission: 'брендовая комиссия',
    MarketplaceServiceItemPackageMaterialsProvision: 'предоставление упаковочных материалов',
    MarketplaceServiceItemPackageRedistribution: 'перераспределение упаковки',
};
