import {
  SELLER_CLIENT_ID,
  SELLER_API_KEY,
  PERFORMANCE_CLIENT_ID,
  PERFORMANCE_CLIENT_SECRET,
} from ".";

export default () => ({
  ozon: {
    SELLER_CLIENT_ID,
    SELLER_API_KEY,
    PERFORMANCE_CLIENT_ID,
    PERFORMANCE_CLIENT_SECRET,
  },
});
